### ISSUE TITLE
Always use bundled database when updating the App

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#107]
1. Download an App update.
2. The User should then be using the bundled database, which should be the latest database.

**Comment by bettar** [comment]
Only amiko_db_full_idx ?

**Comment by zdavatz** [comment]
Also the Frequency DB and the Interactions DB.

**Comment by bettar** [comment]
The logic is like this: when AmiKo starts it tries to open the DB files located in the Documents directory. If they are not there (this is the case if they have never been updated) it will use files with the same name but from the application bundle. Therefore all we have to do when the application is updated is removing the DB files in the Documents directory, if any, so that the ones in the bundle will be used, until the next download of the DB files.

**Comment by zdavatz** [comment]
I record the build date in code, and compare it with the latest DB update date everytime.

**Comment by zdavatz** [comment]
Also, if the app is too old (e.g. no frequency DB for full text search), we always use bundled one, because there must be frequency DB in app bundle.

**Comment by zdavatz** [comment]
Brian Chan:
	So for example, we build the app today, we have DB (28th Sept) on Google Play. User downloads it today, everything is update to day.
Zeno Davatz:
	correct.
Brian Chan:
	But, if user download the app on 1st Oct? User has DB (28th Sept), the date is 1st Oct. It is not up to date.
